### ISSUE TITLE
switch to https://pkg.go.dev/golang.org/x/exp/slog

### ISSUE THREAD

**Issue by pkieltyka** [go-chi/httplog#16]
Go 1.20 will ship with new "slog" package. We can use it now via "golang.org/x/exp/slog"

Let's upgrade httplog to use it instead :)

**Comment by jellis18** [comment]
Is this still the case for 1.20?

**Comment by Shubhaankar-Sharma** [comment]
@jellis18 as far as i know yes, https://github.com/golang/go/issues/56345 its being tracked here

**Comment by pkieltyka** [comment]
v2 is out
