### ISSUE TITLE
Set writer for logger

### ISSUE THREAD

**Issue by rikkei-minh** [go-chi/httplog#2]
I intend to use your module for our application. It was fine until I need to set the writer to os.Stdout.
I can see the writer is set on config.go like below
`log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr, TimeFormat: time.RFC3339})`
Would you please show me the way to set it to os.Stdout?
And I would be happy if I can configure the TimeFormat too.

Thank you.

**Comment by arjunksofficial** [comment]
I also need the same thing. Let me know if need helps from my side for same

**Comment by jonny7** [comment]
I'd also like to be able to split stderr and stdout logs

**Comment by pkieltyka** [comment]
Yes, its possible but could use a minor PR

**Comment by pkieltyka** [comment]
Solved in v2
