### ISSUE TITLE
v2 panics when headers include set-cookie

### ISSUE THREAD

**Issue by jaredLunde** [go-chi/httplog#27]
Error:
```
panic serving [::1]:50476: runtime error: index out of range [8] with length 8
goroutine 42 [running]:
net/http.(*conn).serve.func1()
....
/.asdf/installs/golang/1.21.3/packages/pkg/mod/github.com/go-chi/httplog/v2@v2.0.0/httplog.go:262 +0x4a8
.....
```

This is the problematic line: https://github.com/go-chi/httplog/blob/ba43194c004ee39512109b99a47bef1277bf0263/httplog.go#L262

**Comment by pkieltyka** [comment]
thanks for report, fixed in https://github.com/go-chi/httplog/commit/c43824d056f3ca9150b5e1b1654de1e15d8071aa and tagged v2.0.1
