### ISSUE TITLE
No err attr output

### ISSUE THREAD

**Issue by Hephyr** [go-chi/httplog#33]
https://github.com/go-chi/httplog/blob/7af1557dccf9f5b0d00b3014926776fdf2ec745d/_example/main.go#L72

Hi there,

I've encountered an issue while running the example code provided in this repository. Specifically, I noticed that the log output does not include the expected error message 'err: err here'.

**Steps to reproduce:**
1. Run the [example](https://github.com/go-chi/httplog/blob/7af1557dccf9f5b0d00b3014926776fdf2ec745d/_example/main.go) code.
2. Access http://localhost:8000/err in browser
3. Observe the log output.

**Expected Behavior:**
I expected to see 'err: err here' in the log output.

**Actual Behavior:**
The 'err: err here' message is missing from the log output.

Environment:
- github.com/go-chi/chi/v5 v5.0.10
- github.com/go-chi/httplog/v2 v2.0.1
- go1.21.1 darwin/arm64
- OS: macOS 14.0

Screenshot:
<img width="1728" alt="image" src="https://github.com/go-chi/httplog/assets/8982774/2cb19442-b655-428b-9cbc-ff1f0b2fffe0">

**Comment by pkieltyka** [comment]
hi :) this was fixed on master. I just tagged v2.0.2 -- can you try that and lmk?

**Comment by Hephyr** [comment]
After upgrading to v2.0.2, it is working fine now. Thank you!

**Comment by pkieltyka** [comment]
Excellent
