### ISSUE TITLE
Logging large response body

### ISSUE THREAD

**Issue by lincolnjpg** [go-chi/httplog#41]
Hello, everyone!
I noticed that there's a [limitation when logging the response body](https://github.com/go-chi/httplog/blob/4a0d7946838b004fe6fd5fedf9ab35ec2f62b88e/httplog.go#L86). In my use case, response body has the error stack trace and, due to its size, many characters are not being logged, making it difficult to properly understand error root cause. Would it be possible to increase the character limitation?

**Comment by pkieltyka** [comment]
its a design goal to keep logs tame, if you want to log a larger body for some reason, its best you handle that with your own custom logger or middleware
