### ISSUE TITLE
The `ResponseHeaders` option does not work currently 

### ISSUE THREAD

**Issue by AnomalRoil** [go-chi/httplog#42]
Currently this does not print Response Headers in the logs:
```
	logger := httplog.NewLogger("http-relay", httplog.Options{
		JSON:     false,
		LogLevel: slog.LevelDebug,
		Concise: false,
		ResponseHeaders: true,
	})
	r.Use(httplog.RequestLogger(logger))
```

This is fixed by either #34 or #39 : the problem is that the `Options` are not being passed to the `RequestLoggerEntry` in the function `NewLogEntry`.

**Comment by pkieltyka** [comment]
thank you for noting, reviewed + merged https://github.com/go-chi/httplog/pull/34
